### ISSUE TITLE
DirectDebit DTO does not reflect JSON data returning from API on listFailedDirectDebits

### ISSUE THREAD

**Issue by little-vista-dev** [sentenial/nuapay-rest-client#17]
We have the following issue:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "remittanceInfo" (class com.sentenial.rest.client.api.directdebit.dto.DirectDebit), not marked as ignorable (10 known properties: "endToEndId", "originalEndToEndId", "scheduleId", "paymentStatus", "representationAttemptNumber", "requestedCollectionDate", "paymentAmount", "exportDate", "actualCollectionDate", "remittanceInformation"])
It appears that instead of remittanceInformation being returned from the API remittanceInfo is returned and the DTO has not been updated to reflect this

**Comment by whelanp** [comment]
Hey @little-vista 

We can confirm that this is an issue with the nuapay-rest-client, we have patched it today.

We also released a new maven artifact. Can you please try using the newer version of the client.

Version *1.0.19.RELEASE*

https://repo.maven.apache.org/maven2/com/sentenial/nuapay-rest-client/1.0.19.RELEASE/

Many Thanks

**Comment by whelanp** [comment]
Closing this issue @little-vista-dev any problems let us know and I'll reopen.
