### ISSUE TITLE
Need to add settlementDateShift field to CreateDirectDebitRequest

### ISSUE THREAD

**Issue by amcegan** [sentenial/nuapay-rest-client#20]
To make the Settlement Date Shift useable it needs to be added to the CreateDirectDebitRequest object.

**Comment by amcegan** [comment]
/(|
           (  :
         __\  \  _____
       (____)  `|
      (____)|   |
       (____).__|
        (___)__.|____

**Comment by ciaran-hanley** [comment]
Hi, added missing property, getter and setter. Lib has been released to maven central and should be available shortly in 1.0.21.RELEASE
