### ISSUE TITLE
No getters in com.sentenial.rest.client.api.directdebit.dto.RejectDetails

### ISSUE THREAD

**Issue by amcegan** [sentenial/nuapay-rest-client#6]
We can not get the values from the RejectDetails DTO without the getters.

**Comment by ciaran-hanley** [comment]
Hi,

Version 1.0.13.RELEASE of nuapay-rest-client should be available on Maven central within the next 2 hours, this version contains the missing getters. 

We will review to see if there are other beans missing getters. 

Thanks

**Comment by amcegan** [comment]
Thanks Ciaran.
