### ISSUE TITLE
ListFailedDirectDebitParameters camel cases parameter names

### ISSUE THREAD

**Issue by knocknarea** [sentenial/nuapay-rest-client#8]
Little Vista 
[url: https://api.sentenialtest.com/faileddirectdebits?rejectCreateFrom=2017-01-29&rejectCreateTo=2017-01-30&technicalRejects=true, error code: 400, response: ErrorResponse [returnCode=7079, returnDescription='Reject To Date' is required]]

If this is called with parameters lowercased, it works. Need a fix for this urgently as we are releasing in a couple of days

**Comment by ciaran-hanley** [comment]
Hi,

We are working on it now. I will notify you of the new version once it is fixed.

Thanks,
Ciaran

**Comment by knocknarea** [comment]
Hello @ciaran-hanley Are we sure this is not an isolated case in term of other end points in the API?

**Comment by ciaran-hanley** [comment]
nuapay-rest-client-1.0.15.RELEASE has been released

**Comment by ciaran-hanley** [comment]
Hi @knocknarea, we will review the rest of the API before closing this issue. The released version should solve your issue with ListFailedDirectDebitParameters 

Thanks

**Comment by ciaran-hanley** [comment]
Following a review of other API's, a further change was required to ListBeneficiariesRequestParameters.java.
1.0.16.RELEASE will be available in Maven central with this fix. 

It may take a couple hours before the new versions appear in Maven central.
